# Generated by Django 2.1.7 on 2020-04-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_data', '0002_setuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(blank=True, max_length=5, null=True, verbose_name='내담자')),
                ('REG_Day', models.DateField(null=True, verbose_name='등록날짜')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='연령')),
                ('sum_medical_A', models.IntegerField(blank=True, default=0, null=True, verbose_name='진료 계획')),
                ('sum_medical_B', models.IntegerField(blank=True, default=0, null=True, verbose_name='각종검사 계획')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Test',
                'db_table': 'bom_test',
                'managed': True,
            },
        ),
    ]
