# Generated by Django 2.1.7 on 2020-04-22 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomsetplan',
            name='setplan_one',
        ),
        migrations.AlterField(
            model_name='bomsetplan',
            name='setplan_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bom_user.BomUser'),
        ),
    ]
