# Generated by Django 2.1.7 on 2020-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_user', '0002_auto_20200422_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomsetplan',
            name='setplan_name',
            field=models.CharField(max_length=10, unique=True, verbose_name='내담자 이름'),
        ),
    ]
