# Generated by Django 2.1.7 on 2020-04-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_user', '0003_auto_20200422_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomsetplan',
            name='sum_case_A',
            field=models.IntegerField(blank=True, null=True, verbose_name='상담 total'),
        ),
        migrations.AddField(
            model_name='bomsetplan',
            name='sum_case_B',
            field=models.IntegerField(blank=True, null=True, verbose_name='1:1교육 total'),
        ),
        migrations.AddField(
            model_name='bomsetplan',
            name='sum_case_C',
            field=models.IntegerField(blank=True, null=True, verbose_name='기초생활지원 total'),
        ),
        migrations.AddField(
            model_name='bomsetplan',
            name='sum_medical_A',
            field=models.IntegerField(blank=True, null=True, verbose_name='진료 total'),
        ),
        migrations.AddField(
            model_name='bomsetplan',
            name='sum_medical_B',
            field=models.IntegerField(blank=True, null=True, verbose_name='각종검사 total'),
        ),
        migrations.AddField(
            model_name='bomsetplan',
            name='sum_medical_C',
            field=models.IntegerField(blank=True, null=True, verbose_name='약지급 total'),
        ),
        migrations.AddField(
            model_name='bomsetplan',
            name='sum_medical_D',
            field=models.IntegerField(blank=True, null=True, verbose_name='예방접종 total'),
        ),
        migrations.AddField(
            model_name='bomsetplan',
            name='sum_medical_E',
            field=models.IntegerField(blank=True, null=True, verbose_name='외부병원 total'),
        ),
        migrations.AddField(
            model_name='bomsetplan',
            name='sum_medical_F',
            field=models.IntegerField(blank=True, null=True, verbose_name='예방의학 total'),
        ),
        migrations.AddField(
            model_name='bomsetplan',
            name='sum_mental_A',
            field=models.IntegerField(blank=True, null=True, verbose_name='정신보건상담 total'),
        ),
        migrations.AddField(
            model_name='bomsetplan',
            name='sum_mental_B',
            field=models.IntegerField(blank=True, null=True, verbose_name='심리검사 total'),
        ),
        migrations.AddField(
            model_name='bomsetplan',
            name='sum_mental_C',
            field=models.IntegerField(blank=True, null=True, verbose_name='심리정서지원프로그램 total'),
        ),
    ]
